### ISSUE TITLE
ImageUrl value being sent as null (Game Ratings Endpoint)

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#181]
The endpoint /games/results/game always sends null for the imageUrl value of the ratings. Need this to get the meme with highest rating for final leaderboard.
![image](https://github.com/sopra-fs23-group-13/meme-it-server/assets/15524263/c92f179c-003f-4350-a1b9-a02b51d821aa)

**Comment by Cnordg** [comment]
This seems to be the same problem as with the textBoxes are imageUrl is part of the Template entity which is stored in a separate table..

**Comment by pablotanner** [comment]
> This seems to be the same problem as with the textBoxes are imageUrl is part of the Template entity which is stored in a separate table..

Maybe we could fix it by making a new endpoint that returns meme with highest score (calculate highest score meme in backend instead of frontend)?

**Comment by Cnordg** [comment]
The problem lies with java persistence, we need to probably store the url directly in meme table and not link it to the template entity. This duplicates data a bit but would solve our problem

On 17 May 2023, at 16:25, Pablo Tanner ***@***.***> wrote:

﻿

This seems to be the same problem as with the textBoxes are imageUrl is part of the Template entity which is stored in a separate table..

Maybe we could fix it by making a new endpoint that returns meme with highest score (calculate highest score meme in backend instead of frontend)?

**Comment by Cnordg** [comment]
Check out this branch [181-imageurl-value-being-sent-as-null-game-ratings-endpoint](https://github.com/sopra-fs23-group-13/meme-it-server/tree/181-imageurl-value-being-sent-as-null-game-ratings-endpoint)
